# ===================================
#  List Column Definitions
# ===================================

columns:
    name:
        label: Характеристика
        width: 30%
        searchable: true

    alt_name:
        label: Альтернативное название

    multiple:
        label: Дополнительно
        type: partial
        path: partials/multiple

    values_list:
        label: Значения
