# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/gromit/catalog/controllers/offers/config/list/columns/offer_properties.yaml

# Model Class name
modelClass: GromIT\Catalog\Models\OfferProperty

filter: $/gromit/catalog/controllers/offers/config/filter/offer_properties.yaml

# Link URL for each record
recordOnClick: "$.popup({ handler: 'onOpenValueForm', size: 'huge', extraData: { offer_property_id: ':id' } })"

# Message to display if the list is empty
noRecordsMessage: Нет привязанных характеристик

# Display checkboxes next to each record
showCheckboxes: true

structure:
    showTree: false
    showReorder: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: toolbars/offer_properties
