# ===================================
#  List Column Definitions
# ===================================

columns:
    name:
        label: Группа
        searchable: true

    alt_name:
        label: Альтернативное название
        searchable: true

    slug:
        label: Slug
