# ===================================
#  List Column Definitions
# ===================================

columns:

    name:
        label: Категория
        type: partial
        path: partials/name
        searchable: true

    slug:
        label: Slug

    is_active:
        label: Статус
        type: partial
        path: partials/is_active
        clickable: false

    edit_category:
        label: '&nbsp;'
        type: partial
        path: partials/edit_category
        clickable: false
        searchable: false
        sortable: false
