type: form
actionBtnLabel: Добавить
actionOnClick: onAddGroup
closeOnSuccess: true
modelClass: GromIT\Catalog\Models\Group
form:
    fields:

        group_id:
            label: Набор характеристик
            type: dropdown

popupId: product-properties-group
