# ===================================
#  List Column Definitions
# ===================================

columns:

    property_name:
        label: Характеристика
        type: partial
        path: partials/property_name

    savedValues:
        label: Значения

    multiple:
        label: '&nbsp;'
        type: partial
        path: partials/multiple_properties
