scopes:

    byGroups:
        label: Наборы характеристик
        modelClass: GromIT\Catalog\Models\ProductProperty
        type: group
        scope: byFilterGroups
        options: getFilterGroupsOptions
